### ISSUE TITLE
Issue executing jcliff module in Travis testing

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/automate-jcliff#7]
Hit the following issue when testing jcliff module in Travis

```
    The full traceback is:
    Traceback (most recent call last):
      File "/tmp/ansible_VxL8YJ/ansible_module_jcliff.py", line 190, in <module>
        main()
      File "/tmp/ansible_VxL8YJ/ansible_module_jcliff.py", line 187, in main
        has_changed, has_failed, result = choice_map.get(module.params['state'])(data=module.params)
      File "/tmp/ansible_VxL8YJ/ansible_module_jcliff.py", line 107, in jcliff_present
        generateRuleFromTemplate(data, rulesdir)
      File "/tmp/ansible_VxL8YJ/ansible_module_jcliff.py", line 41, in generateRuleFromTemplate
        renderFromTemplate(rulesdir,'drivers.j2', "drivers-" + driver['driver_name'] + ".yml", driver)
      File "/tmp/ansible_VxL8YJ/ansible_module_jcliff.py", line 23, in renderFromTemplate
        template = env.get_template(template_name)
      File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
        template = self.loader.load(self, name, globals)
      File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 178, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: drivers.j2
    
    fatal: [centos-systemd]: FAILED! => {
        "changed": false, 
        "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_VxL8YJ/ansible_module_jcliff.py\", line 190, in <module>\n    main()\n  File \"/tmp/ansible_VxL8YJ/ansible_module_jcliff.py\", line 187, in main\n    has_changed, has_failed, result = choice_map.get(module.params['state'])(data=module.params)\n  File \"/tmp/ansible_VxL8YJ/ansible_module_jcliff.py\", line 107, in jcliff_present\n    generateRuleFromTemplate(data, rulesdir)\n  File \"/tmp/ansible_VxL8YJ/ansible_module_jcliff.py\", line 41, in generateRuleFromTemplate\n    renderFromTemplate(rulesdir,'drivers.j2', \"drivers-\" + driver['driver_name'] + \".yml\", driver)\n  File \"/tmp/ansible_VxL8YJ/ansible_module_jcliff.py\", line 23, in renderFromTemplate\n    template = env.get_template(template_name)\n  File \"/usr/lib/python2.7/site-packages/jinja2/environment.py\", line 791, in get_template\n    return self._load_template(name, self.make_globals(globals))\n  File \"/usr/lib/python2.7/site-packages/jinja2/environment.py\", line 765, in _load_template\n    template = self.loader.load(self, name, globals)\n  File \"/usr/lib/python2.7/site-packages/jinja2/loaders.py\", line 113, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File \"/usr/lib/python2.7/site-packages/jinja2/loaders.py\", line 178, in get_source\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: drivers.j2\n", 
        "module_stdout": "", 
        "msg": "MODULE FAILURE", 
        "rc": 1
```

**Comment by rpelisse** [comment]
I think we can close this now!

**Comment by sabre1041** [comment]
@rpelisse agree. closing
